export interface PostSection {
  heading?: string
  divider?: boolean
  text?: string[]
  code?: {
    language: string
    snippet: string
  }
  callout?: string
  list?: string[]
}

export interface Post {
  slug: string
  title: string
  date: string
  readTime: string
  tag: string
  excerpt: string
  sections: PostSection[]
}

export const posts: Post[] = [
  {
    "slug": "we-were-fine-yesterday",
    "title": "We Were Fine Yesterday",
    "date": "09.09.26",
    "readTime": "30 min read",
    "tag": "Personal Note",
    "excerpt": "On modern silence, grieving an imagined future, and learning to answer your own life.",
    "sections": [
      {
        "text": [
          "There is something strangely cruel about modern relationships.",
          "Sometimes, nobody breaks up with you.",
          "Nobody says, “I don't love you anymore.”",
          "Nobody says, “Please don't text me again.”",
          "Nobody gives you a final conversation where you can cry, argue, ask questions, embarrass yourself, accept the truth, and finally close the chapter.",
          "Sometimes, the person simply becomes busy.",
          "At least, that is what they say.",
          "And then one day, you realize that the person who used to be a part of your everyday life has quietly become a person you are no longer supposed to look for.",
          "There is no dramatic ending.",
          "No slammed door.",
          "No final scene.",
          "Just silence.",
          "And somehow, silence gives your mind much more work than rejection ever could.",
          "Because rejection gives you an answer.",
          "Silence gives you possibilities.",
          "Maybe they are busy.",
          "Maybe something happened.",
          "Maybe they are upset.",
          "Maybe they will come back.",
          "Maybe they miss you.",
          "Maybe they never cared as much as you thought.",
          "Maybe they care too much and are trying to stay away.",
          "Maybe you did something wrong.",
          "Maybe you did nothing wrong at all.",
          "And when you don't know which one is true, your mind becomes a detective with no evidence.",
          "It investigates everything.",
          "Every old conversation.",
          "Every late night.",
          "Every nickname.",
          "Every promise.",
          "Every “good morning.”",
          "Every heart.",
          "Every little sentence that once seemed ordinary.",
          "You start looking backward because there is nothing left to look forward to.",
          "That is how I found myself remembering someone who was never physically standing beside me.",
          "Someone I had never sat with in a café.",
          "Someone whose hand I had never held.",
          "Someone whose room I had never entered.",
          "Someone whose voice I could not simply hear by walking across a hallway.",
          "And yet, somehow, her absence could make a perfectly normal room feel empty.",
          "That was the part I could not understand.",
          "How can someone who was never physically here leave such a physical emptiness behind?",
          "Maybe that is one of the strangest things about being alive in this generation.",
          "We have built a world where people can enter our lives without ever entering our rooms."
        ]
      },
      {
        "divider": true,
        "text": [
          "It started innocently enough.",
          "That is how these things usually start.",
          "Nobody wakes up one morning and decides, “Today I am going to become emotionally attached to someone I met online.”",
          "You talk.",
          "Then you talk a little more.",
          "Then you realize you enjoy talking.",
          "Then you begin waiting for their messages.",
          "Then you start telling them things you don't tell everyone.",
          "Then their name appearing on your screen changes your mood.",
          "And somewhere between one ordinary conversation and another, the person stops being “someone I talk to.”",
          "They become part of your day.",
          "That transition is so quiet that you rarely notice it happening.",
          "At first, you can put your phone down.",
          "Then you check it once.",
          "Then again.",
          "Then you start wondering why they haven't replied.",
          "Eventually, you don't even need a notification.",
          "You just pick up your phone.",
          "Not because you have something to do.",
          "Because maybe they have written something.",
          "And when they have, even a tiny message can feel disproportionately important.",
          "A stupid joke.",
          "A random question.",
          "A “what are you doing?”",
          "A nickname.",
          "Something completely insignificant to the rest of the world can become the best part of your day.",
          "That happened to me.",
          "She had her own way of talking.",
          "There were affectionate little names.",
          "There was teasing.",
          "There were moments when the conversation was completely meaningless and somehow still felt meaningful.",
          "She could call me “buddhu.”",
          "Sometimes “babu.”",
          "And honestly, it is funny how easily the human brain gets attached to sounds.",
          "A word that means almost nothing in isolation can become precious when it comes from the right person.",
          "You could hear ten people say the same thing and not care.",
          "Then one particular person says it, and suddenly you remember it months later.",
          "That is probably one of the quiet tricks affection plays on us.",
          "It does not make everything objectively special.",
          "It makes ordinary things special to you."
        ]
      },
      {
        "divider": true,
        "text": [
          "For a while, everything felt normal.",
          "Not perfect.",
          "Not some movie where every conversation magically fits into a romantic soundtrack.",
          "Just normal.",
          "And perhaps that is why it mattered.",
          "Real attachment rarely feels dramatic while you are living inside it.",
          "It is built from tiny things.",
          "The conversations you have when neither of you has anything particularly interesting to say.",
          "The random updates.",
          "The jokes that would make absolutely no sense to anyone else.",
          "The habit of telling someone what happened during your day.",
          "The comfort of knowing there is somebody somewhere who will probably be there when you open your phone.",
          "You don't realize how much those things matter until they disappear.",
          "That is when you discover that routine can become emotional architecture.",
          "Remove one small piece and suddenly the whole structure feels different.",
          "There was a point when she told me something that stayed in my head.",
          "She said that life might make either of us busy.",
          "But she would be by my side until I left her.",
          "At the time, it sounded comforting.",
          "Maybe even obvious.",
          "People say things like that when they are close.",
          "You don't stop and analyze every sentence.",
          "You don't ask for a signed contract.",
          "You simply believe the person because believing them feels natural.",
          "I remember telling her that even a smile or a heart would be enough.",
          "There did not need to be some elaborate explanation every time.",
          "I did not need paragraphs.",
          "I just wanted some small indication that the connection still existed.",
          "That was enough.",
          "Or at least, I thought it would be.",
          "It is strange how little we actually ask from the people we become attached to.",
          "Sometimes we say we want love.",
          "But what we really want is reassurance.",
          "A message.",
          "A sign.",
          "A tiny reminder that we have not disappeared from someone's world."
        ]
      },
      {
        "divider": true,
        "text": [
          "The problem with attachment is that once you care enough, your brain begins protecting itself.",
          "You start imagining the ending before it happens.",
          "I did that too.",
          "I asked questions about leaving.",
          "What if you leave?",
          "What if one day you disappear?",
          "What if things change?",
          "Maybe those questions were annoying.",
          "Maybe they were unnecessary.",
          "Maybe they were simply the result of caring too much.",
          "I don't know.",
          "But there is something important about fear that I understand now.",
          "When you are afraid of losing someone, sometimes you keep asking them to promise they won't leave.",
          "And ironically, the more you ask, the more you remind yourself that leaving is possible.",
          "You turn a hypothetical future into something that already occupies your mind.",
          "You start preparing for a disaster that may never happen.",
          "Until one day, it does.",
          "And then all those old questions come back.",
          "Not as questions.",
          "As accusations against yourself.",
          "“You knew.”",
          "“You asked.”",
          "“You should have seen it.”",
          "“You should have understood.”",
          "“You should have been less attached.”",
          "“You should have noticed something.”",
          "The human mind is incredibly talented at blaming itself after the fact.",
          "It takes information you did not have at the time and pretends you should have known it.",
          "That is not how life works.",
          "We make decisions using the information available to us at that moment.",
          "The future does not send us spoilers."
        ]
      },
      {
        "divider": true,
        "text": [
          "Then life became busy.",
          "Or at least, that was what I was told.",
          "She said she was a bit busy these days.",
          "She said she would try to text whenever she got free time.",
          "She told me not to get her wrong.",
          "She told me she knew I was mature enough to understand her side.",
          "On paper, there was nothing cruel about those words.",
          "In fact, they were almost considerate.",
          "She did not insult me.",
          "She did not say anything horrible.",
          "She did not tell me I was worthless.",
          "She simply said she was busy.",
          "And yet, something about it felt different.",
          "Because sometimes the words themselves are not the message.",
          "The change in behavior is.",
          "And shortly afterward, I was blocked.",
          "That was the part that made everything confusing.",
          "Because “I'm busy” and “I'm disappearing from your life” are two very different things.",
          "If someone tells you they are busy, you expect time to pass.",
          "You expect them to return eventually.",
          "Maybe tomorrow.",
          "Maybe next week.",
          "Maybe after exams.",
          "Maybe when life settles down.",
          "But when the person disappears completely, your brain starts asking questions the original message never answered.",
          "Was “busy” really the reason?",
          "Was there something else?",
          "Did she get overwhelmed?",
          "Did she stop feeling the same?",
          "Did something happen in her life?",
          "Was it family?",
          "Was it circumstances?",
          "Was it fear?",
          "Was it simply a change of heart?",
          "Or was I just trying to find a complicated explanation because the simplest one hurt too much?",
          "I still don't know.",
          "And that is probably the most honest answer I can give.",
          "I don't know."
        ]
      },
      {
        "divider": true,
        "text": [
          "There is a particular kind of pain that comes from not knowing why someone left.",
          "It is different from ordinary heartbreak.",
          "If someone tells you, “I don't want this relationship anymore,” you may hate the answer, but at least the answer exists.",
          "You can fight it.",
          "You can accept it.",
          "You can disagree with it.",
          "Eventually, you can build your life around it.",
          "But when you don't know why someone disappeared, your mind keeps the door unlocked.",
          "Not because you consciously want it open.",
          "Because there is no definitive reason to close it.",
          "This is why unanswered questions can be more exhausting than bad answers.",
          "A bad answer can hurt once.",
          "An unanswered question can hurt every morning.",
          "Every night.",
          "Every time you open the same app.",
          "Every time you see their name.",
          "Every time your phone vibrates and your heart jumps before your brain has even processed the notification.",
          "And the worst part is that nothing actually happened in that moment.",
          "Your phone simply buzzed.",
          "But for half a second, hope appeared.",
          "Then disappeared.",
          "That half second is enough."
        ]
      },
      {
        "divider": true,
        "text": [
          "There were nights when I woke up around two or three in the morning.",
          "Sometimes closer to four.",
          "The room would be dark.",
          "The hostel would be quiet.",
          "Everyone else seemed to be living their own lives somewhere behind closed doors.",
          "And for a moment, half asleep, my brain would create something I desperately wanted to be true.",
          "Maybe she messaged.",
          "Maybe she came back.",
          "Maybe there was a notification.",
          "Maybe everything was fine.",
          "Then I would check the phone.",
          "Nothing.",
          "That is a particularly cruel experience because dreams don't care about reality.",
          "In a dream, people return.",
          "People apologize.",
          "People explain.",
          "People send messages.",
          "People say the things you wanted to hear.",
          "And then you wake up.",
          "For a few seconds, you still believe it happened.",
          "Then reality arrives.",
          "No message.",
          "No explanation.",
          "Just another ordinary morning.",
          "Except it does not feel ordinary anymore."
        ]
      },
      {
        "divider": true,
        "text": [
          "I used to think missing someone meant wanting them back.",
          "Now I am not sure.",
          "Sometimes missing someone simply means missing who you were when they were around.",
          "That version of yourself who had someone to tell things to.",
          "That version of yourself who had something to look forward to.",
          "That version of yourself who could send a stupid message without thinking about whether it was stupid.",
          "That version of yourself who had a familiar notification waiting somewhere in the day.",
          "Maybe we don't always miss the person.",
          "Sometimes we miss the feeling their presence created inside us.",
          "And that distinction matters.",
          "Because if you don't understand it, you can spend months chasing a person when what you actually want is the feeling of being wanted.",
          "You can mistake loneliness for love.",
          "You can mistake attention for intimacy.",
          "You can mistake familiarity for permanence.",
          "And once you are lonely enough, almost any connection can begin to look romantic.",
          "That realization hit me harder than I expected."
        ]
      },
      {
        "divider": true,
        "text": [
          "After she disappeared, I started noticing something about myself.",
          "When I felt lonely, I wanted to talk to a girl.",
          "Not necessarily her.",
          "Just someone.",
          "A random conversation could suddenly feel important.",
          "Someone replying nicely could make me wonder if there was something more.",
          "Someone asking about my life could make my brain start writing an entire relationship before the second conversation was over.",
          "It sounds ridiculous when written down.",
          "But loneliness is not particularly logical.",
          "When you are emotionally hungry, a little attention can taste like a full meal.",
          "And that is dangerous.",
          "Because you start assigning meaning to things before they have earned it.",
          "Someone asks you a question.",
          "You think they are interested.",
          "Someone adds you somewhere.",
          "You think they like you.",
          "Someone responds quickly.",
          "You think there is chemistry.",
          "Someone is kind.",
          "You think there is a connection.",
          "Maybe there is.",
          "Maybe there isn't.",
          "But your loneliness wants the answer to be yes.",
          "It wants evidence that you are still wanted.",
          "It wants someone to fill the empty space.",
          "And if you are not careful, you stop looking for people and start looking for relief.",
          "Those are not the same thing."
        ]
      },
      {
        "divider": true,
        "text": [
          "I began understanding that my problem was not simply that someone had left.",
          "It was that I had allowed one connection to become too important.",
          "My day had started revolving around another person's availability.",
          "My mood could change because of a message.",
          "My night could feel good because of a conversation.",
          "My morning could feel empty because there was nothing waiting on the screen.",
          "That is a dangerous amount of power to give another person.",
          "Not because they are necessarily bad.",
          "But because people are unpredictable.",
          "People get busy.",
          "People change.",
          "People get scared.",
          "People meet new people.",
          "People have families, responsibilities, problems, fears and private battles you may never know about.",
          "Sometimes people leave without giving you a reason that makes sense to you.",
          "And sometimes, despite everything they once said, they still leave.",
          "That is one of the hardest things to accept.",
          "A promise made yesterday does not control tomorrow.",
          "A person can genuinely mean what they say at one moment and still make a different decision later.",
          "That does not automatically mean they were lying.",
          "It means humans are complicated.",
          "We are not contracts."
        ]
      },
      {
        "divider": true,
        "text": [
          "There was another thing I struggled with.",
          "If she left, did that mean everything before it was fake?",
          "Did the affection mean nothing?",
          "Were the conversations meaningless?",
          "Was I stupid for believing them?",
          "That question can destroy you if you let it.",
          "Because when something ends badly, we have a strange habit of rewriting the entire story.",
          "If the ending hurts, we decide the beginning must have been fake.",
          "If someone leaves, we convince ourselves they never cared.",
          "If a relationship fails, we tell ourselves we imagined the good parts.",
          "It gives us a clean explanation.",
          "But clean explanations are not always true.",
          "Something can be real and temporary.",
          "A conversation can be genuine even if it does not last forever.",
          "Someone can care about you and still be unable to continue.",
          "A connection can matter and still end.",
          "We want permanence because permanence makes us feel safe.",
          "But permanence is not the definition of reality.",
          "A sunset is real even though it ends.",
          "A holiday is real even though you return home.",
          "A good conversation is real even though eventually you say goodnight.",
          "Maybe some people enter our lives for a chapter rather than the entire book.",
          "The chapter still happened."
        ]
      },
      {
        "divider": true,
        "text": [
          "I also had to fight the urge to find answers myself.",
          "The internet makes this incredibly easy.",
          "When someone disappears, you can search.",
          "Facebook.",
          "Instagram.",
          "Chess.",
          "Old profiles.",
          "Mutual connections.",
          "Other accounts.",
          "There are always more doors.",
          "And when you are hurting, every door looks like an opportunity.",
          "Maybe if I find her somewhere else, I can ask what happened.",
          "Maybe she blocked me accidentally.",
          "Maybe she will explain.",
          "Maybe she will answer.",
          "Maybe I can just send one neutral message.",
          "Just one.",
          "That phrase, “just one,” is one of the biggest lies we tell ourselves when we are emotionally attached.",
          "Just one message.",
          "Just one account.",
          "Just one explanation.",
          "Just one attempt.",
          "But a boundary is still a boundary even when you don't like the reason behind it.",
          "If someone blocks you, the painful thing to do is often the healthiest thing.",
          "Stop.",
          "Don't create another account.",
          "Don't hunt for another platform.",
          "Don't turn the internet into a map leading to someone who has chosen not to be reachable.",
          "Because sometimes the answer you want is not waiting behind another profile.",
          "Sometimes the answer is the absence itself.",
          "Not necessarily an explanation.",
          "But a decision.",
          "She is not available to you right now.",
          "That is enough information to change what you do next.",
          "It may not be enough information to satisfy your heart.",
          "But it is enough information to respect her boundary.",
          "And perhaps, eventually, your own dignity."
        ]
      },
      {
        "divider": true,
        "text": [
          "Still, understanding something intellectually does not mean feeling it emotionally.",
          "That is another lesson I learned.",
          "You can know something is over and still hope.",
          "You can know you should not message and still want to.",
          "You can understand boundaries and still miss someone.",
          "You can tell yourself, “Move on,” and then spend an hour remembering one conversation.",
          "Healing is not a straight line.",
          "It is not:",
          "Day 1: devastated.",
          "Day 2: slightly better.",
          "Day 3: completely fine.",
          "Real life is messier.",
          "One day you think you are okay.",
          "Then a song plays.",
          "A random phrase reminds you of them.",
          "You see something they would have liked.",
          "You open an app without thinking.",
          "And suddenly you are back there.",
          "That does not mean you made no progress.",
          "It means memory is not a staircase.",
          "It is more like weather.",
          "Sometimes the storm returns.",
          "You just learn not to rebuild your house every time it rains."
        ]
      },
      {
        "divider": true,
        "text": [
          "There were moments when the loneliness became so heavy that everything else started feeling pointless.",
          "Studying felt difficult.",
          "Reading felt difficult.",
          "Writing felt difficult.",
          "Even things I normally cared about felt far away.",
          "That was when I began realizing how dangerous emotional pain can become when it starts spreading into every other part of your life.",
          "One problem becomes ten.",
          "You lose focus.",
          "Then you fall behind.",
          "Then you feel guilty for falling behind.",
          "Then you feel worse.",
          "Then you look for distraction.",
          "Then you feel guilty about wasting time.",
          "Then you think about money.",
          "Then you think about your future.",
          "Then you compare yourself with everyone around you.",
          "Then you wonder what you are even doing with your life.",
          "And suddenly the original problem is no longer just about a girl.",
          "It has become about your identity.",
          "Your career.",
          "Your loneliness.",
          "Your friendships.",
          "Your habits.",
          "Your future.",
          "Your self worth.",
          "That is when heartbreak stops being a romantic problem and becomes a life problem.",
          "And that is also when you have to be careful.",
          "Because one person leaving should not be allowed to take the rest of your life with them."
        ]
      },
      {
        "divider": true,
        "text": [
          "I started thinking about money more too.",
          "Not because money could bring her back.",
          "It couldn't.",
          "But because money began to represent something else.",
          "Control.",
          "Independence.",
          "Security.",
          "The ability to take care of myself.",
          "The ability to buy something for someone I love without checking my bank balance ten times.",
          "The ability to build something.",
          "To earn.",
          "To have options.",
          "To not feel helpless.",
          "I had responsibilities and dreams outside of this story.",
          "I wanted to become good enough at software development and problem solving to get an internship.",
          "I wanted to build projects.",
          "I wanted to earn.",
          "I wanted to change my body.",
          "I wanted to become more disciplined.",
          "I wanted to become someone my family could depend on.",
          "I wanted to be able to help my brother.",
          "I wanted a future that felt bigger than whatever was happening on my phone.",
          "But heartbreak has a strange ability to make a huge future feel smaller than a single unread message.",
          "That is why getting your life back matters.",
          "Not to prove anything to the person who left.",
          "Not to make them regret it.",
          "Not to post some dramatic transformation online.",
          "You do it because your life was always bigger than the relationship.",
          "You just temporarily forgot."
        ]
      },
      {
        "divider": true,
        "text": [
          "I also began looking differently at my friendships.",
          "When you are lonely, you will often spend time with whoever is available.",
          "Even if they are not taking you anywhere.",
          "Sometimes you sit around people who spend money every day drinking and smoking.",
          "You join because you don't want to be alone.",
          "Then you spend money you did not want to spend.",
          "You smoke even though you had decided not to.",
          "You drink even though you know tomorrow will feel worse.",
          "You laugh for a few hours.",
          "Then you return to your room.",
          "And the silence is still there.",
          "That is when you understand something uncomfortable.",
          "Distraction is not the same as healing.",
          "You can be surrounded by ten people and still be lonely.",
          "You can spend an entire night laughing and still wake up feeling empty.",
          "You can keep your mind busy all day and still think about the same person the moment the room becomes quiet.",
          "Noise does not cure loneliness.",
          "Sometimes it only postpones it."
        ]
      },
      {
        "divider": true,
        "text": [
          "So what do you do when the person you were used to talking to is no longer there?",
          "At first, you look for replacements.",
          "Then you realize people are not replacements.",
          "A new person is not a new version of the old person.",
          "A new conversation should not be forced to carry the weight of an old one.",
          "That is unfair to both people.",
          "You cannot meet someone new and ask them, silently, to repair what someone else broke.",
          "They did not break it.",
          "They should not have to fix it.",
          "And you cannot make every new girl you talk to audition for the role of the person you lost.",
          "That is not connection.",
          "That is comparison disguised as connection.",
          "So maybe the first step is learning to be alone without immediately trying to escape it.",
          "Not forever.",
          "Just long enough to understand yourself again."
        ]
      },
      {
        "divider": true,
        "text": [
          "There is a version of loneliness that is actually useful.",
          "It sounds strange.",
          "But when there is nobody to constantly text, you eventually start hearing your own thoughts.",
          "At first, that can be horrible.",
          "You notice how distracted you have become.",
          "You notice how much of your happiness was dependent on external validation.",
          "You notice how often you reach for your phone.",
          "You notice how quickly you interpret kindness as affection.",
          "You notice how desperately you want someone to tell you that you matter.",
          "And then you have a choice.",
          "You can keep searching for someone to tell you.",
          "Or you can start building a life that makes you believe it yourself.",
          "That takes longer.",
          "It is less exciting.",
          "There is no notification sound when you become more disciplined.",
          "Nobody sends you a heart when you finish a difficult problem.",
          "Nobody calls you “babu” because you went to the gym.",
          "Nobody tells you that you look good because you finally slept properly.",
          "The rewards are quieter.",
          "But they last longer.",
          "You study.",
          "You build.",
          "You exercise.",
          "You save money.",
          "You learn.",
          "You make something.",
          "You help your family.",
          "You become better.",
          "And slowly, your life starts producing its own reasons to wake up."
        ]
      },
      {
        "divider": true,
        "text": [
          "I am still not sure what happened to her.",
          "Maybe someday I will know.",
          "Maybe I never will.",
          "There are explanations I have imagined.",
          "Family.",
          "Circumstances.",
          "Fear.",
          "Being overwhelmed.",
          "Changing feelings.",
          "Being busy.",
          "Maybe one of them is true.",
          "Maybe none of them are.",
          "The dangerous part is that when you have no explanation, your imagination will happily manufacture one.",
          "And imagination has no obligation to be accurate.",
          "It can make you the villain.",
          "It can make her the villain.",
          "It can create an entire secret story involving people and events you have never seen.",
          "That is why sometimes you have to stop investigating.",
          "Not because the truth does not matter.",
          "But because you don't have access to it.",
          "There are some questions you cannot solve by thinking harder.",
          "That is one of them."
        ]
      },
      {
        "divider": true,
        "text": [
          "I wish heartbreak came with a clear checklist.",
          "Step one: cry.",
          "Step two: delete memories.",
          "Step three: become successful.",
          "Step four: stop caring.",
          "Step five: magically become attractive and mysterious.",
          "Step six: person who left regrets everything.",
          "Unfortunately, life is not that generous.",
          "You can do everything “right” and still miss them.",
          "You can block yourself from checking their profile and still wonder what they are doing.",
          "You can fill your schedule and still remember them at night.",
          "You can meet new people and still compare them.",
          "You can become stronger and still have soft spots.",
          "Healing does not mean the memory disappears.",
          "It means the memory stops controlling the present.",
          "That is the goal.",
          "Not amnesia.",
          "Freedom."
        ]
      },
      {
        "divider": true,
        "text": [
          "Maybe one day I will look back at this period and realize that losing one person forced me to meet another person.",
          "Myself.",
          "The version of me that had been hidden underneath constant conversations, notifications, expectations and distractions.",
          "The version of me who had dreams before the heartbreak.",
          "The version of me who wanted to build things.",
          "The version of me who wanted to earn.",
          "The version of me who wanted to become physically stronger.",
          "The version of me who wanted to make something meaningful.",
          "The version of me who wanted to take care of his family.",
          "The version of me who wanted a future that could not fit inside a chat window.",
          "Maybe that person never disappeared.",
          "Maybe he was simply distracted."
        ]
      },
      {
        "divider": true,
        "text": [
          "There is still a part of me that wishes she had explained.",
          "I won't pretend otherwise.",
          "I wish there had been one proper conversation.",
          "Not necessarily to change her mind.",
          "Just to understand.",
          "I wish she had said what changed.",
          "I wish I had known what was happening on her side.",
          "I wish I did not have to reconstruct the ending from a few messages and a block.",
          "I wish the story had ended with words instead of silence.",
          "But wishing for a different ending does not create one.",
          "At some point, you have to stop editing the past.",
          "You cannot rewrite the last conversation.",
          "You cannot send a message back in time.",
          "You cannot make yourself less attached.",
          "You cannot unknow what happened.",
          "All you can control is what you do with the story now.",
          "And maybe that is where the story becomes yours again."
        ]
      },
      {
        "divider": true,
        "text": [
          "I think there is something else worth saying.",
          "Online relationships are often dismissed as less real.",
          "People say things like:",
          "“You never even met.”",
          "“It was just chatting.”",
          "“How can you get attached to someone you haven't physically met?”",
          "I used to think maybe there was something embarrassing about getting hurt this badly over someone I knew through a screen.",
          "Now I don't think that is fair.",
          "Humans have always formed emotional bonds through distance.",
          "Letters.",
          "Phone calls.",
          "Long distance relationships.",
          "Emails.",
          "Messages.",
          "The technology changes.",
          "The human brain does not.",
          "If someone makes you laugh every day, listens to your problems, remembers small details about you, comforts you when you're down and becomes part of your routine, your brain does not sit there and say:",
          "“Don't worry, this is digital, so attachment disabled.”",
          "It doesn't work like that.",
          "Connection is connection.",
          "The screen is simply the road it travels through.",
          "The danger is not that online feelings are fake.",
          "The danger is that online intimacy can sometimes grow faster than real life has a chance to test it.",
          "You can know someone's thoughts without knowing their daily reality.",
          "You can know what they say without knowing everything they are dealing with.",
          "You can feel close without having experienced ordinary life together.",
          "And that can make the connection feel incredibly intense while still leaving huge parts of the person unknown.",
          "That does not make the feelings fake.",
          "It makes them incomplete.",
          "And maybe that distinction is important."
        ]
      },
      {
        "divider": true,
        "text": [
          "I also learned that people can be incredibly important to each other without belonging to each other.",
          "That sounds simple.",
          "It is not.",
          "When you care about someone, part of you wants certainty.",
          "You want to know where you stand.",
          "You want to know they won't disappear.",
          "You want to know the future.",
          "You want reassurance.",
          "But another person is never something you own.",
          "They are free to change.",
          "Free to leave.",
          "Free to become distant.",
          "Free to choose a life you are not part of.",
          "And you are free too.",
          "That freedom is painful when you are losing someone.",
          "But it is also what makes connection meaningful in the first place.",
          "If someone stays only because they have no choice, staying means nothing.",
          "The beautiful part of being loved is that the person could leave, but chooses not to.",
          "And the painful part is that sometimes they eventually choose differently."
        ]
      },
      {
        "divider": true,
        "text": [
          "For a while, I wanted to know whether she missed me.",
          "That question occupied far more space in my head than it deserved.",
          "Does she think about me?",
          "Does she remember me?",
          "Does she ever open our old conversation?",
          "Does she regret leaving?",
          "Does she want to text?",
          "Does she ever feel the same emptiness?",
          "I wanted some evidence that my absence existed on her side too.",
          "Because if I was hurting alone, somehow that made the whole thing feel more humiliating.",
          "But eventually I realized something.",
          "I may never know.",
          "And even if I knew, what would it change?",
          "If she misses me, she still chose distance.",
          "If she doesn't miss me, I still have to move forward.",
          "If she cared, it doesn't undo what happened.",
          "If she didn't, it doesn't erase what I felt.",
          "The answer to “Does she miss me?” is emotionally fascinating and practically useless.",
          "That was a difficult lesson.",
          "We sometimes spend enormous amounts of energy trying to answer questions that cannot improve our lives even when answered."
        ]
      },
      {
        "divider": true,
        "text": [
          "Maybe I was looking for proof that I mattered.",
          "But perhaps the better question is:",
          "Do I matter to myself now?",
          "That question is much harder.",
          "Because it requires action.",
          "It is easy to want someone else to choose you.",
          "It is harder to choose yourself on an ordinary Tuesday when nobody is watching.",
          "To study when you don't feel like studying.",
          "To go to the gym when your mood is terrible.",
          "To stop spending money just to keep up with friends.",
          "To put the cigarette down.",
          "To sleep properly.",
          "To work on the project.",
          "To learn something difficult.",
          "To stop checking the phone.",
          "To stop looking for another account.",
          "To stop replaying the same conversation.",
          "To get up.",
          "Again.",
          "And again.",
          "Those things are not dramatic.",
          "Nobody makes a movie about them.",
          "But maybe that is where recovery actually happens.",
          "In boring moments.",
          "In small decisions.",
          "In ordinary mornings."
        ]
      },
      {
        "divider": true,
        "text": [
          "I don't know what happens next.",
          "Maybe she never returns.",
          "Maybe one day there is a message.",
          "Maybe life surprises me.",
          "Maybe years from now, her name will mean nothing more than a chapter from college.",
          "Maybe I will remember the whole thing and laugh at how seriously I took certain conversations.",
          "Maybe I will remember it with a little sadness.",
          "Maybe both.",
          "People become stories eventually.",
          "Even the people who once felt like the whole world.",
          "The funny thing is, the world doesn't actually stop.",
          "Classes continue.",
          "Assignments remain due.",
          "The gym is still open.",
          "The washing machine still needs clothes.",
          "People still eat dinner.",
          "Friends still make stupid jokes.",
          "The sun still comes up.",
          "Your phone still needs charging.",
          "Life has an almost insulting ability to continue normally while you are falling apart inside.",
          "At first, that feels cruel.",
          "Later, you realize it is a gift.",
          "Because life continuing means you get another chance to continue too."
        ]
      },
      {
        "divider": true,
        "text": [
          "Perhaps that is the real lesson.",
          "Not that you should never love someone online.",
          "Not that you should never become attached.",
          "Not that you should stop trusting people.",
          "Not that every promise is a lie.",
          "Not that everyone eventually leaves.",
          "Those are all easy conclusions.",
          "Too easy.",
          "The harder lesson is this:",
          "Love people, but don't abandon yourself while doing it.",
          "Care deeply.",
          "Laugh.",
          "Talk until midnight.",
          "Give people stupid nicknames.",
          "Remember their favorite things.",
          "Buy them something because they once mentioned liking it.",
          "Make memories.",
          "Let yourself be happy.",
          "But keep a life that belongs to you.",
          "Keep your goals.",
          "Keep your friends who actually want the best for you.",
          "Keep your health.",
          "Keep your money.",
          "Keep your curiosity.",
          "Keep your identity.",
          "Keep something that remains standing even if one person walks away.",
          "Because love should add a room to your house.",
          "It should not become the entire house."
        ]
      },
      {
        "divider": true,
        "text": [
          "I used to think the worst part of someone leaving was that they took something with them.",
          "Now I think the worst part is that, for a while, you believe they did.",
          "They took your happiness.",
          "They took your motivation.",
          "They took your peace.",
          "They took your ability to focus.",
          "They took your future.",
          "They took something from you.",
          "But eventually you realize something.",
          "They didn't take those things.",
          "You temporarily handed them over.",
          "And if you handed them over, you can take them back.",
          "Slowly.",
          "One piece at a time.",
          "The first piece might be sleep.",
          "Then food.",
          "Then exercise.",
          "Then study.",
          "Then work.",
          "Then laughter.",
          "Then ambition.",
          "Then confidence.",
          "Then peace.",
          "Not all at once.",
          "Just one thing.",
          "Then another."
        ]
      },
      {
        "divider": true,
        "text": [
          "Maybe I will never know whether she was telling the truth when she said she was busy.",
          "Maybe she genuinely was.",
          "Maybe she wasn't.",
          "Maybe she cared.",
          "Maybe she still does.",
          "Maybe she stopped.",
          "Maybe she was overwhelmed.",
          "Maybe she had reasons I will never understand.",
          "I can live with not knowing.",
          "Not today.",
          "Maybe not tomorrow.",
          "But eventually.",
          "Because there are things more important than an unanswered question.",
          "My life.",
          "My future.",
          "The people who are still here.",
          "The person I am becoming.",
          "And the strange, stubborn possibility that something good can exist after something painful ends."
        ]
      },
      {
        "divider": true,
        "text": [
          "There is one thing I know now.",
          "I did not imagine that the connection mattered to me.",
          "I did not imagine the happiness.",
          "I did not imagine the conversations.",
          "I did not imagine how attached I became.",
          "And I do not need to call those feelings stupid just because the story ended differently than I wanted.",
          "I can admit that I cared.",
          "I can admit that I miss her.",
          "I can admit that I wish things had gone differently.",
          "I can admit that I sometimes still hope for a message.",
          "And at the same time, I can choose not to chase one.",
          "Both can be true.",
          "That might be what maturity actually looks like.",
          "Not having no feelings.",
          "Having feelings and still knowing what to do with them."
        ]
      },
      {
        "divider": true,
        "text": [
          "One day, I imagine, there will be a night when I wake up at three in the morning and don't reach for the phone.",
          "Not because I suddenly stopped caring.",
          "Because I stopped needing an answer.",
          "The room will still be dark.",
          "The hostel will still be quiet.",
          "The world will still be asleep.",
          "And for once, my first thought won't be:",
          "“Did she message?”",
          "It will just be:",
          "“I need to sleep.”",
          "And I will turn over.",
          "Close my eyes.",
          "And go back to sleep.",
          "That sounds like a very small victory.",
          "Maybe it is.",
          "But after spending nights waiting for a notification that may never come, I think small victories deserve more respect."
        ]
      },
      {
        "divider": true,
        "text": [
          "There was a time when I thought the story ended when she left.",
          "Maybe it didn't.",
          "Maybe that was only the point where the story stopped being about us.",
          "Maybe the next part is about me.",
          "About learning why I attach so deeply.",
          "About learning why loneliness makes attention feel like love.",
          "About learning that someone else's decision cannot decide my value.",
          "About learning that boundaries matter even when they hurt.",
          "About learning that closure cannot always be requested.",
          "About learning that memories can stay without becoming chains.",
          "About learning that a person can be important without being permanent.",
          "About learning that the future cannot be sacrificed to understand the past.",
          "And most importantly, about learning how to stand inside my own life again."
        ]
      },
      {
        "divider": true,
        "text": [
          "I still don't have a perfect ending.",
          "Maybe there isn't one.",
          "Real life rarely gives you those.",
          "There is no dramatic final conversation.",
          "No perfect explanation.",
          "No beautiful soundtrack.",
          "No sentence that suddenly makes everything make sense.",
          "Sometimes a person simply becomes absent.",
          "And you remain.",
          "You wake up.",
          "You brush your teeth.",
          "You go to class.",
          "You sit in the lab.",
          "You eat whatever the hostel serves.",
          "You work on your projects.",
          "You go to the gym.",
          "You complain about money.",
          "You laugh with friends.",
          "You get annoyed.",
          "You make plans.",
          "You fail at some of them.",
          "You try again.",
          "And somewhere in between all those ordinary things, the person you thought you could never stop thinking about becomes a thought that visits occasionally.",
          "Then less often.",
          "Then unexpectedly.",
          "Then gently.",
          "Until one day you realize you are remembering them without wanting anything from them.",
          "That, perhaps, is closure.",
          "Not forgetting.",
          "Not hating.",
          "Not pretending.",
          "Just remembering without reaching."
        ]
      },
      {
        "divider": true,
        "text": [
          "Maybe that is the strangest thing about losing someone.",
          "You think you are grieving the end of a relationship.",
          "Then slowly you realize you are also grieving an imagined future.",
          "The conversations you thought you would have.",
          "The jokes you thought you would make.",
          "The ordinary days you assumed would exist.",
          "The version of the future where that person was still around.",
          "That future never technically existed.",
          "But your mind had already lived in it.",
          "That is why losing an imagined future can hurt almost as much as losing a real past.",
          "You are not only saying goodbye to what happened.",
          "You are saying goodbye to what you thought might happen.",
          "And nobody teaches us how to grieve possibilities.",
          "There is no ceremony for them.",
          "No photograph.",
          "No final moment.",
          "Just a quiet realization:",
          "“That was never going to happen.”",
          "And then another small piece of you lets go."
        ]
      },
      {
        "divider": true,
        "text": [
          "I think that is what I am learning now.",
          "Some people leave without giving us the ending we deserved.",
          "Some conversations remain unfinished.",
          "Some questions never get answers.",
          "Some people become memories before we are ready for them to.",
          "And sometimes, the most loving thing you can do is not hold on harder.",
          "Sometimes it is to open your hand.",
          "Not because what you held was worthless.",
          "Because it mattered.",
          "And because something mattered, you should be grateful that it existed rather than destroy yourself trying to make it exist forever.",
          "I don't know whether I will ever completely stop missing her.",
          "Maybe I don't need to.",
          "Maybe the goal was never to forget.",
          "Maybe the goal is simply to remember without breaking.",
          "To look back without running backward.",
          "To care without chasing.",
          "To love without losing yourself.",
          "To accept the silence without letting it silence your own life.",
          "And eventually, to wake up one morning and realize that you are no longer waiting.",
          "You are living.",
          "That is probably the ending I want.",
          "Not her coming back.",
          "Not revenge.",
          "Not regret.",
          "Not some cinematic reunion.",
          "Just this:",
          "I want to become so present in my own life that I no longer need someone else's message to prove that the day is worth living.",
          "And maybe someday, when I look back at the person I was during those nights, checking a silent phone at three in the morning, I won't laugh at him.",
          "I won't call him weak.",
          "I won't call him stupid.",
          "I'll probably just understand.",
          "He cared.",
          "He got attached.",
          "He got hurt.",
          "He didn't know what to do with the silence.",
          "So he waited.",
          "And then, eventually, he learned not to.",
          "He put the phone down.",
          "He looked around.",
          "His life was still there.",
          "Messy.",
          "Unfinished.",
          "Expensive.",
          "Complicated.",
          "Full of things he still had to figure out.",
          "But alive.",
          "Waiting for him.",
          "And for the first time in a long time, he decided to answer.",
          "Not her message.",
          "His own life.",
          "- Toni"
        ]
      }
    ]
  },
  {
    slug: 'sometimes-all-you-need-is-someone-to-say-yes',
    title: 'Sometimes, All You Need Is Someone to Say Yes',
    date: '09.09.26',
    readTime: '4 min read',
    tag: 'Product Craft',
    excerpt: 'Why I built Chalo: on chai, spontaneity, and making software whose only goal is to help two people put their phones away.',
    sections: [
      {
        text: [
          'There are these tiny moments in life that don\'t really qualify as plans.',
          'You feel like having chai.',
          'You want to go for a walk.',
          'You suddenly feel like playing football.',
          'You want someone to sit with while you study.',
          'Nothing serious. Nothing that needs a calendar invite.',
          'Just a small thought:',
        ],
        callout: '“Anyone up for this?”',
      },
      {
        text: [
          'And most of the time, we don\'t ask.',
          'We think our friends are busy. We don\'t know who to call. We don\'t know where everyone is. And the moment passes.',
          'I kept thinking about those moments. What if they didn\'t have to?',
        ],
      },
      {
        heading: 'Maybe meeting people shouldn\'t be so complicated',
        text: [
          'The internet has made it incredibly easy to find almost anything.',
          'A song. A restaurant. A movie. A stranger who lives 10,000 kilometres away and happens to like the same obscure band.',
          'But finding someone nearby who simply wants to grab chai right now? Somehow, that\'s still surprisingly difficult.',
          'That\'s where Chalo started. Not as a social network. Not as a place to collect followers. Just as a little idea:',
        ],
        callout: 'What if you could say what you feel like doing, and find someone nearby who feels the same?',
      },
      {
        text: [
          'You want chai. Someone else wants chai.',
          'Maybe that\'s enough.',
        ],
      },
      {
        heading: 'The idea was simple',
        text: [
          'I wanted Chalo to turn small thoughts into real moments.',
          'You open the app. You see something happening nearby: a chai break, a study session, a football game, a photography walk, a late-night food plan.',
          'You join. And then you leave your phone in your pocket.',
          'That\'s probably my favorite part of the idea:',
        ],
        callout: 'The best version of Chalo is one you don\'t spend much time using. Because the app isn\'t supposed to become the destination. The person you meet is.',
      },
      {
        heading: 'So I tried to make it feel different',
        text: [
          'I didn\'t want Chalo to feel like another social media app asking for your attention. There is already enough of that.',
          'I wanted it to feel a little calmer. A little warmer. Like opening a door and finding that something is already happening on the other side.',
          'That influenced everything: from the colors and spacing to the way activities are presented and how quickly you can create one.',
          'I kept coming back to one question: Can this feel as easy as asking a friend? Because people don\'t think in forms and database fields. They think:',
        ],
        callout: '“Let\'s go for chai.”',
      },
      {
        text: [
          'The software has to do the complicated part. Not the person.',
        ],
      },
      {
        heading: 'Then I started building it',
        text: [
          'Once the idea felt real enough, I wanted to see if I could make it real enough to use.',
          'So I built Chalo from the ground up. The mobile experience uses React Native and Expo. The backend uses FastAPI and PostgreSQL.',
          'I built the onboarding and authentication flows, profiles, activity creation, discovery, joining, and meetup management.',
          'But somewhere along the way, I realized that building Chalo wasn\'t really about learning another framework. It was teaching me something I hadn\'t thought much about before:',
        ],
        callout: 'Good software often begins with understanding a feeling.',
      },
      {
        text: [
          '“I\'m bored.” “I\'m new here.” “I want to meet people.” “I don\'t want to go alone.”',
          'Those aren\'t technical requirements. But they are where the product begins.',
          'The job of the software is to quietly turn that feeling into an opportunity.',
        ],
      },
      {
        heading: 'And maybe that\'s enough',
        text: [
          'I don\'t know exactly what Chalo will become. Maybe it\'ll become something bigger. Maybe it\'ll stay a small experiment that taught me how I like to build. I\'m okay with either.',
          'Because I like the thought that somewhere, someday, someone might open Chalo and see:',
        ],
        callout: '“Chai in 20 minutes. 2 spots left.”',
      },
      {
        text: [
          'And instead of scrolling past it, they go. They meet someone they\'ve never met before. They talk about absolutely nothing important. They laugh. The chai gets cold.',
          'And for a little while, the internet has done something surprisingly useful. It helped two people put their phones away.',
        ],
        callout: 'That\'s why I built Chalo. Not to help people connect online. To give them a reason to connect offline.',
      },
      {
        text: [
          '- Toni',
        ],
      },
    ],
  },
]
